/**
 * Original ASCII art source file.
 * This file contains the human-readable ASCII art with actual Unicode characters.
 *
 * Generated from here
 * @see https://patorjk.com/software/taag/#p=display&f=Rebel&t=AMPHI&x=none&v=4&h=4&w=80&we=false
 *
 * DO NOT import this file directly in bundled code!
 * Use ascii.ts instead, which is generated by running `bun run generate:ascii`
 *
 * The build process converts these Unicode characters to a template format
 * that survives Bun's bundler without getting escaped.
 */

export const ASCII_ART_SOURCE = `
   █████████   ██████   ██████ ███████████  █████   █████ █████
  ███░░░░░███ ░░██████ ██████ ░░███░░░░░███░░███   ░░███ ░░███
 ░███    ░███  ░███░█████░███  ░███    ░███ ░███    ░███  ░███
 ░███████████  ░███░░███ ░███  ░██████████  ░███████████  ░███
 ░███░░░░░███  ░███ ░░░  ░███  ░███░░░░░░   ░███░░░░░███  ░███
 ░███    ░███  ░███      ░███  ░███         ░███    ░███  ░███
 █████   █████ █████     █████ █████        █████   █████ █████
░░░░░   ░░░░░ ░░░░░     ░░░░░ ░░░░░        ░░░░░   ░░░░░ ░░░░░
`
